#!/usr/bin/env bash
# Installs and configures HAProxy to load balance between web-01 and web-02 using roundrobin

apt-get update -y
apt-get install haproxy -y

# Backup default config
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Overwrite haproxy config
cat <<EOL > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 10d4f3192fad.fa45f440.alu-cod.online:80 check
    server web-02 10d4f3192fad.fa45f440.alu-cod.online:80 check
EOL

# Start HAProxy
service haproxy restart
