#!/usr/bin/env bash
# Configures Nginx to include a custom HTTP header 'X-Served-By' with the server's hostname

apt-get update -y
apt-get install nginx -y

# Ensure hostname is set
hostnamectl set-hostname web-02

# Add the custom header
sed -i '/^server {/a \    add_header X-Served-By "$hostname";' /etc/nginx/sites-available/default

# Restart Nginx (without systemctl)
service nginx restart
