#!/usr/bin/env bash
# Install Nginx and set up a web page with "Holberton School"

apt-get update -y
apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

service nginx start
