#!/usr/bin/env bash
# Adds a 301 redirect from /redirect_me to YouTube

apt-get update -y
apt-get install nginx -y

sed -i '/location \/ {/a \ \n    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

service nginx restart
